# Qutebrowser Config
# Ruwey (ruwey.com)

# Keybindings {{{
binds:
  normal:
    <Ctrl+Shift+f>: 'spawn -u qute-pass --username-pattern ''((?<=^user: ).*|(?<=login: ).*)''
    --username-target secret --dmenu-invocation ''bash -c "dmenu -l 5 -w $(xdotool getactivewindow)"'''
    <Ctrl+Shift+p>: 'spawn -u qute-pass --username-pattern ''((?<=^user: ).*|(?<=login: ).*)''
    --username-target secret --password-only --dmenu-invocation ''bash -c "dmenu -l 5 -w $(xdotool getactivewindow)"'''
    <Ctrl+j>: tab-move -
    <Ctrl+k>: tab-move +
    <Ctrl+j>: tab-move +
    <Ctrl+k>: tab-move -
    j: run-with-count 2 scroll down
    k: run-with-count 2 scroll up
    d: null
    dd: tab-close
    po: set-cmd-text -s :open -p
    pO: set-cmd-text :open -p {url:pretty}
    zi: zoom-in
    zo: zoom-out
    zz: zoom
    # Toggle Ad Blocking
    ",ta": config-cycle content.blocking.adblock.enabled
    ",tb": config-cycle tabs.show never always
    ",ts": config-cycle statusbar.show never always
    ",ff": 'spawn -u qute-pass --username-pattern ''((?<=^user: ).*|(?<=login: ).*)''
    --username-target secret'
    ",fp": 'spawn -u qute-pass --username-pattern ''((?<=^user: ).*|(?<=login: ).*)''
    --username-target secret --password-only'
    ",fu": 'spawn -u qute-pass --username-pattern ''((?<=^user: ).*|(?<=login: ).*)''
    --username-target secret --username-only'
    ",vo": spawn -u view_in_mpv
  insert:
    <Ctrl+e>: null
    <Ctrl+Shift+f>: 'spawn -u qute-pass --username-pattern ''((?<=^user: ).*|(?<=login: ).*)''
    --username-target secret --dmenu-invocation ''bash -c "dmenu -l 5 -w $(xdotool getactivewindow)"'''
    <Ctrl+Shift+p>: 'spawn -u qute-pass --username-pattern ''((?<=^user: ).*|(?<=login: ).*)''
    --username-target secret --password-only --dmenu-invocation ''bash -c "dmenu -l 5 -w $(xdotool getactivewindow)"'''
    #<Ctrl+Shift+f>u: 'spawn -u qute-pass --username-pattern ''((?<=^user: ).*|(?<=login: ).*)''
    #--username-target secret --username-only'
# }}}

# Settings {{{
settings:
  global:
    spellcheck.languages:
      - en-US
    url.searchengines:
      DEFAULT: "https://duckduckgo.com/?q={}" # Default Search Engine: DuckDuckGO
      gh: "https://github.com/search?q={}" # Github
      yt: "https://www.youtube.com/results?search_query={}" # Youtube
      r/: "https://reddit.com/r/{}"
      r/s: "https://www.reddit.com/search/?q={}"
      itad: "https://isthereanydeal.com/search/?q={}" # Is There Any Deal
      aur: "https://aur.archlinux.org/packages/?O=0&K={}"
      protondb: "https://www.protondb.com/search?q={}"
      wirecutter: "https://www.nytimes.com/wirecutter/search/?s={}"
      twt: "https://twitter.com/search?q={}"
    content.notifications.enabled: false
    content.autoplay: false
    auto_save.session: true
    content.blocking.adblock.lists:
      #- "https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt"
      - "https://easylist.to/easylist/easylist.txt"
      - "https://easylist.to/easylist/easyprivacy.txt"
        #- "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext"
        #- "https://curben.gitlab.io/malware-filter/urlhaus-filter-online.txt"
        #- "https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt"
        #- "https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt"

    #"*://www.reddit.com/*":
    # Fix comments not loading on reddit. (Ads are unblock-able anyway)
    #content.blocking.adblock.enabled: false
# }}}

# sup
